### PR TITLE
Small typos

### PR DESCRIPTION
**Pull request by kabutz**
A few small typos. The one I'm not sure you'll agree with is to reword "equals" to "equal". We cannot say that two objects "equals" each other. We could say that an object equals another.

### CODE REVIEW

**Comment by forax** [comment]
Thank you !

**Comment by kabutz** [comment]
Actually just saw now that the files that I should've been changing are the MD files. Do you generate one from the other?

**Comment by forax** [comment]
I generate the .md and .ipyrb from the .jsh using
```
  java build/build.java
```

**Comment by kabutz** [comment]
Ha, glad I "accidentally" changed the correct file :-)

**Pull request merged**
